GET http://localhost:5000/warden/leaveapplications

####

POST http://localhost:5000/warden/leaveapplications/update
Content-Type: application/json

{"_id":"6267b58e9bbdf70e140d6f69", "status":"declined"}

####

POST http://localhost:5000/admin/student
Content-Type: application/json

{"name": "Preet", "email": "preet@gmail.com", "phone": 1234567890, "password":"qwerty123", "cpassword":"qwerty123", "rollno":"19BCP098","room":613, "block":"B", "course":"btech", "quota":"dasa"}

####

POST http://localhost:5000/admin/warden
Content-Type: application/json

{"name": "warden", "email": "warden@gmail.com", "phone": 1234567890, "password":"qwerty123", "cpassword":"qwerty123", "block":"B"}

####
POST http://localhost:5000/login
Content-Type: application/json

{   "email":"preetstudent@gmail.com",
    "password":"admin123"
}

####
POST http://localhost:5000/student/leaveform
Content-Type: application/json

{
    "email":"preetstudent@gmail.com", "appdate":"2001-07-25", "depdate":"2001-07-25", "deptime":"7:00", "arrdate":"2001-07-26", "arrtime":"21:00", "reason":"homevisit", "destination":"vadodara", "cpersonName":"jesus", "cpersonRelation":"hangman", "cpersonPhone":9000123920
}